version: "3.7"

services:
  server:
    build: ./server
    command: "sh -c 'yarn install && yarn run dev'"
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
      - l2b-test-server-node-modules:/app/node_modules
    depends_on:
      - redis
    links:
      - redis
    networks:
      - l2b-test

  client:
    build: ./client
    ports:
      - 8081:8080
    volumes:
      - ./client:/app
      - l2b-test-client-node-modules:/app/node_modules
    networks:
      - l2b-test

  redis:
    container_name: fullstack-test-redis
    image: redis:7.0.11
    ports:
      - 6379:6379
    networks:
      - l2b-test


networks:
  l2b-test:
    driver: bridge

volumes:
  l2b-test-server-node-modules:
  l2b-test-client-node-modules:
